### ISSUE TITLE
4.1 Software Estimation

### ISSUE THREAD

**Issue by Cassandra-Fu** [hanz105/INF2001-Team-Project-P8-3#10]
Task title id: 4.1

Task: Make an estimation of the project's resource and time needs

Goals: Make an estimation of the project's software needs.

Success or completion criteria: Complete the calculations for the project's software needs.

Allocated time: 3 days.

Start Date and End date of the issue: 19/09/23 - 21/09/23

Owner: Steven

Status: Refer to Github status

Priority: High

**Comment by AstralAurora** [comment]
- Calculated the software estimation for this project.

- Calculations have been committed to report.

- Work was completed on time

- No changes to success or completion criteria of task

- Start and End date: 19/09/23 - 21/09/23

**Comment by AstralAurora** [comment]
Work done, issue closed.
