### ISSUE TITLE
1.3.1 Questionnaire for Follow up email with client

### ISSUE THREAD

**Issue by Cassandra-Fu** [hanz105/INF2001-Team-Project-P8-3#11]
Task Title ID: 1.3.1

About this task: Create and send the questionnaire for the follow up email with the client.

Goal: To gather additional information after the interview.

The success criteria: To gather additional information using the questionnaire. 

Allocated Time: 1 day.

Start and End date: 19/09/23 - 19/09/23

Owner: Ng Teng Hui.

Status: Refer to GitHub status.

Priority: Refer to GitHub priority.

**Comment by AstralAurora** [comment]
- Create a questionnaire for the client to fill up when they can, to be sent through email. 

- Information gathered has been committed to report.

- Work was completed on time

- No changes to success or completion criteria of task

Start and End date: 19/09/23 - 19/09/23

**Comment by AstralAurora** [comment]
Work completed
