### ISSUE TITLE
2.4 Activity Diagram

### ISSUE THREAD

**Issue by Cassandra-Fu** [hanz105/INF2001-Team-Project-P8-3#13]
Task Title ID: 2.4

About this task: Create the activity diagram.

Goal: To create a satisfactory activity diagram.

The success criteria: To create an understandable activity diagram useful for our project.

Allocated Time: 2 days.

Start and End date: 19/09/23 - 20/09/23.

Owner: Steven.

Status: Refer to GitHub status.

Priority: High.

**Comment by AstralAurora** [comment]
- Created a understandable and satisfactory activity diagram that is useful to showcase our project.

- Activity diagram has been committed to report.

- Work was completed on time

- No changes to success or completion criteria of task

- Start and End date: 19/09/23 - 20/09/23

**Comment by AstralAurora** [comment]
Work done, issue closed.
