### ISSUE TITLE
2.3.1 Review Use Case Description

### ISSUE THREAD

**Issue by AstralAurora** [hanz105/INF2001-Team-Project-P8-3#14]
Task Title ID: 2.3.1

About this task: Review the use case description as a team.

Goal: Finalise the use case descriptions a team.

Success criteria: Successfully finalise the use case description.

Allocated Time: 1 day.

Start and End date: 19/09/23 - 19/09/23

Owner: Evan

Status: Refer to GitHub status.

Priority: Refer to GitHub priority.

**Comment by EvanChua22** [comment]
Reviewing the use case descriptions as a team.

Descriptions are stated

On track

No

20/09/23 - 20/09/23

**Comment by AstralAurora** [comment]
Work done, issue closed.
