### ISSUE TITLE
2.2.1 Review Use Case Diagram

### ISSUE THREAD

**Issue by AstralAurora** [hanz105/INF2001-Team-Project-P8-3#15]
Task Title ID: 2.2.1

About this task: Review the use case diagram as a team.

Goal: Finalise the use case diagram as a team.

The success criteria: Successfully finalise the use case diagram.

Allocated Time: 1 day.

Start and End date: 19/09/23 - 19/09/23

Owner: Evan.

Status: Refer to GitHub status.

Priority: Refer to GitHub priority.

**Comment by EvanChua22** [comment]
Reviewing the use case diagram as a team.

Diagram is created

On track

No

20/09/23 - 20/09/23

**Comment by AstralAurora** [comment]
Work done, issue closed.
