### ISSUE TITLE
2.1 Functional Requirements

### ISSUE THREAD

**Issue by AstralAurora** [hanz105/INF2001-Team-Project-P8-3#17]
Task title ID: 2.1

About this task: This task features all the requirements that the system should behave like on a functional level.

Goals: To list all the possible functional requirements that the system should have. 

Success or completion criteria: All functional requirements are listed out.

Allocated time: 5 days

Start and end date: 15/09/2023 - 19/09/2023

Owner: Evan

Status: Completed

Priority: Refer to Github priority

**Comment by EvanChua22** [comment]
Finding all the functional requirements that the system should have.
Functional requirements gathered and listed out.
On track.
No.
19/09/23 - 19/09/23

**Comment by AstralAurora** [comment]
Work done, issue closed.
