### ISSUE TITLE
2. Requirements Analysis

### ISSUE THREAD

**Issue by StevieeeLau** [hanz105/INF2001-Team-Project-P8-3#18]
Task title ID: 2 

Task: Gather requirements and analyse them.

Goals: Analyse the requirements we had gathered.

Success or Completion criteria: Satisfactory requirements gathered and analysed, to be put in the report.

Allocated Time: 7 days.

Start date and End date: 11/09/23 - 14/09/23

Owner: Steven 

Status: Refer to GitHub.

Priority: High.

**Comment by AstralAurora** [comment]
- Gathered the requirements for the project from the client and observations.

- Information gathered has been committed to report.

- Work was completed on time
 
- No changes to success or completion criteria of task
 
- Start and End date: 11/09/23 - 14/09/23

**Comment by AstralAurora** [comment]
Work done.
