### ISSUE TITLE
4. Project Estimation and Plan

### ISSUE THREAD

**Issue by StevieeeLau** [hanz105/INF2001-Team-Project-P8-3#19]
Task title ID: 4

Task: To plan the entire development effort in detail.

Goals: To estimate the duration and cost of the project

Success or completion criteria: Complete the project estimation.

Allocated Time: 3 days.

Start date and End date of the issue: 19/09/23 - 21/09/23

Owner: Steven

Status: Refer to GitHub status

Priority: High

**Comment by AstralAurora** [comment]
- Calculated the estimated duration and cost of the project.

- Calculations have been committed to the report.

- Work was completed on time

- No changes to success or completion criteria of task

- Start and End date: 19/09/23 - 19/09/23

**Comment by AstralAurora** [comment]
Work done, issue closed.
