### ISSUE TITLE
1.4 Background Literature

### ISSUE THREAD

**Issue by StevieeeLau** [hanz105/INF2001-Team-Project-P8-3#3]
Task Title ID: 1.4

Task Detail:
Research on currently available workload scheduling software.

Goal: 
Understand the common features used in workload scheduling software.
What should be important in a workload scheduling software.

Success Criteria: 
Understand the domain and how features in different software can be applied to the project

Allocated Time: 2 days

Start and End date: 
14/09/23 - 15/09/23

Status: Completed

Priority: Medium

**Comment by Cassandra-Fu** [comment]
- Gathered research on the currently available workload scheduling software.

- Information gathered has been committed to report.

- Work was completed on time

- No changes to success or completion criteria of task

Start and End date: 14/09/23 - 15/09/23

**Comment by AstralAurora** [comment]
Work done, issue closed.
