### ISSUE TITLE
2.2 Use Case Diagram

### ISSUE THREAD

**Issue by hanz105** [hanz105/INF2001-Team-Project-P8-3#5]
Task Detail:
Identify Actors & Use Cases.

Goals:
Have a better understanding of the actors and interactions with system solution.

Success or completion criteria: All use cases have met updated requirements.

Allocated time: 5 day

Start and End date: 12/09/23 - 17/09/23

Owner: Teng Hui.

Status: Refer to GitHub status.

Priority: Refer to GitHub priority.

**Comment by Cassandra-Fu** [comment]
1. Diagram was done by discussing requirements and delegated among the whole team. Afterwards, each use case was reviewed and edited. by each other.
2. Work had been updated in report.
3. Work has already been completed.
4. No changes to completion criteria
5. 19/9/23 - 19/9/23

**Comment by AstralAurora** [comment]
Work completed and closed
