### ISSUE TITLE
8. Architecture Design & Detailed Design

### ISSUE THREAD

**Issue by AstralAurora** [hanz105/INF2001-Team-Project-P8-3#58]
Task Title ID: 8

About this task: To create and confirm the details of our architecture and detailed design diagrams.

Goal: To update the architecture and detailed design diagrams into the M3 Report.

The success criteria: When the review of the architecture & detailed design diagrams are deemed completed to update into the M3 Report after a review.

Allocated Time: 5 days.

Start and End date: 1/11/23 - 5/11/23.

Owner: Hannah.

Status: Refer to GitHub status.

Priority: High.

**Comment by StevieeeLau** [comment]
Tasks from 8.1 and 8.2 to create the details of the architecture design, and the detailed design diagrams are completed and task 8.3 to validate the designs is completed as well, thus overall task is accomplished.

Work has been committed to report.

Work was completed on time.

No changes to success or completion criteria of task.

Start and End date: 01/11/23 - 06/11/23.

**Comment by StevieeeLau** [comment]
Work done, issue closed.
