### ISSUE TITLE
8.2 Detailed Design Diagram

### ISSUE THREAD

**Issue by AstralAurora** [hanz105/INF2001-Team-Project-P8-3#59]
Task Title ID: 8.2

About this task: To create the details of our detailed design diagram.

Goal: To update the detailed design diagram into the M3 Report.

The success criteria: When the review of the detailed design diagram is deemed completed to update into the M3 Report after a review.

Allocated Time: 2 days.

Start and End date: 3/11/23 - 4/11/23.

Owner: Evan.

Status: Refer to GitHub status.

Priority: High.

**Comment by StevieeeLau** [comment]
The details for the detailed design diagram noted in main task 8 have been created.

Work has been committed to report.

Work was completed on time.

No changes to success or completion criteria of task.

Start and End date: 4/11/23 - 5/11/23.

**Comment by StevieeeLau** [comment]
Work done, issue closed.
