### ISSUE TITLE
2.3 Use Case Description

### ISSUE THREAD

**Issue by hanz105** [hanz105/INF2001-Team-Project-P8-3#6]
Task title ID: 2.3

About this task: This task provides details about the description of each respective use cases. Description includes the flow of the use case showing the description, actors, preconditions, postconditions, flow of activities and alternative scenarios. 

Goals: To find the number of transactions which helps us in the project estimation. 

Success or completion criteria: Flow of activities is clear in each description

Allocated time: 5 days

Start and end date: 15/09/2023 - 19/09/2023

Owner: Evan

Status: Refer to Github status

Priority: High

**Comment by EvanChua22** [comment]
Descriptions of the use cases which includes the flow of the use case

Descriptions are stated

On track

No

19/09/23 - 19/09/23

**Comment by AstralAurora** [comment]
Work done, issue closed.
