### ISSUE TITLE
8.1 Architecture Design Diagram

### ISSUE THREAD

**Issue by AstralAurora** [hanz105/INF2001-Team-Project-P8-3#60]
Task Title ID: 8.1

About this task: To create the details of our architecture design diagram.

Goal: To update the architecture design diagram into the M3 Report.

The success criteria: When the review of the architecture diagram is deemed completed to update into the M3 Report after a review.

Allocated Time: 2 days.

Start and End date: 1/11/23 - 2/11/23.

Owner: Hannah.

Status: Refer to GitHub status.

Priority: High.

**Comment by StevieeeLau** [comment]
The details for the architecture design diagram noted in main task 8 have been created.

Work has been committed to report.

Work was completed on time.

No changes to success or completion criteria of task.

Start and End date: 1/11/23 - 3/11/23.

**Comment by StevieeeLau** [comment]
Work done, issue closed.
