### ISSUE TITLE
8.3 Architecture & Detailed Design Validation

### ISSUE THREAD

**Issue by AstralAurora** [hanz105/INF2001-Team-Project-P8-3#61]
Task Title ID: 8.3

About this task: To confirm the details of our architecture and detailed design diagrams.

Goal: To update the architecture and detailed design diagrams into the M3 Report.

The success criteria: When the review of the architecture & detailed design diagrams are deemed completed to update into the M3 Report after a review.

Allocated Time: 1 day.

Start and End date: 5/11/23 - 5/11/23.

Owner: Evan.

Status: Refer to GitHub status.

Priority: High.

**Comment by StevieeeLau** [comment]
The details for the architecture design diagram and detailed design diagrams done in tasks 8.1 and 8.2 have been reviewed and updated into the M3 report.

Work has been committed to report.

Work was completed on time.

No changes to success or completion criteria of task.

Start and End date: 5/11/23 - 6/11/23.

**Comment by StevieeeLau** [comment]
Work done, issue closed.
