### ISSUE TITLE
11.1 Create Prototype

### ISSUE THREAD

**Issue by AstralAurora** [hanz105/INF2001-Team-Project-P8-3#62]
Task Title ID: 11.1

About this task: To create the prototype.

Goal: To input the details of the prototype into the M3 report.

The success criteria: When the information of the prototype is reviewed and deemed appropriate to be placed into the M3 report.

Allocated Time: 3 days.

Start and End date: 14/11/23 - 16/11/23.

Owner: Cassandra.

Status: Refer to GitHub status.

Priority: High.

**Comment by StevieeeLau** [comment]
The input for the prototype details noted in main task 11 have been created.

Work has been committed to report.

Work was completed on time.

No changes to success or completion criteria of task.

Start and End date: 15/11/23 - 18/11/23.

**Comment by StevieeeLau** [comment]
Work done, issue closed.
