### ISSUE TITLE
11.2 Review Prototype

### ISSUE THREAD

**Issue by AstralAurora** [hanz105/INF2001-Team-Project-P8-3#63]
Task Title ID: 11.2

About this task: To review the completed prototype.

Goal: To input the details of the prototype into the M3 report.

The success criteria: When the information of the prototype is reviewed and deemed appropriate to be placed into the M3 report.

Allocated Time: 1 day.

Start and End date: 17/11/23 - 17/11/23.

Owner: Cassandra.

Status: Refer to GitHub status.

Priority: High.

**Comment by StevieeeLau** [comment]
The prototype details noted in main task 11 have been reviewed

Work has been committed to report.

Work was completed on time.

No changes to success or completion criteria of task.

Start and End date: 18/11/23 - 19/11/23.

**Comment by StevieeeLau** [comment]
Work done, issue closed.
