### ISSUE TITLE
1.3 Follow up email with client

### ISSUE THREAD

**Issue by hanz105** [hanz105/INF2001-Team-Project-P8-3#7]
Task Title ID # 1.3

About this task: Create a follow up email to clarify other requirements, including use case diagram, observations, and work break down structure.

Goal: To clarify other requirements from the client.

The success criteria: To clarify work done is satisfactory.

Allocated Time: 1 days.

Start and End date: 19/09/23 - 19/09/23.

Owner: Hannah.

Status: Refer to GitHub status.

Priority: Refer to GitHub priority.

**Comment by AstralAurora** [comment]
- Create a email to follow up with the client.

- Information gathered has been committed to report.

- Work was completed on time

- No changes to success or completion criteria of task

- Start and End date: 19/09/23 - 19/09/23

**Comment by AstralAurora** [comment]
Work done, issue closed.
