### ISSUE TITLE
1.1 Interview with client

### ISSUE THREAD

**Issue by hanz105** [hanz105/INF2001-Team-Project-P8-3#8]
Task Title ID: 1.1

About this task: Meet up with the client to gather further requirements for the project

Goal: To gather additional requirement specifications not originally mentioned and clarify them.

The success criteria: To gather enough information from the client to work on the rest of the project.

Allocated Time: 1 day.

Start and End date: 13/09/23 - 13/09/23

Owner: P8-3.

Status: Refer to GitHub status.

Priority: High.

**Comment by Cassandra-Fu** [comment]
1. The interview was done using a face-to-face interview. Meeting minutes was also added.
2.  Work has been committed to report.
3. The date of the interview was late but it did not affect the completion deadline. 
4. Start and End date: 13/09/23 - 13/09/23

**Comment by Cassandra-Fu** [comment]
Issue has been closed.
