### ISSUE TITLE
4.2 Gantt Chart (until M3)

### ISSUE THREAD

**Issue by Cassandra-Fu** [hanz105/INF2001-Team-Project-P8-3#9]
Task Title ID: 4.2

About this task: Create the Gantt chart to display the work break down until M3.

Goal: Create and keep up to date the Gantt chart for our project plans.

The success criteria: Create and keep up to date Gantt chart for our project.

Allocated Time: Entire Project Time. (Will be constantly updated when necessary)

Start and End date: 1/09/23 - 24/11/23

Owner: Ng Teng Hui.

Status: Refer to GitHub status.

Priority: High.

**Comment by AstralAurora** [comment]
Created and updated the Gantt chart, keep it constantly up to date.

Work has been committed to Gantt chart.

No changes to success or completion criteria of task.

Start and End date: 1/09/23 - 24/11/23.

**Comment by AstralAurora** [comment]
Work done, issue closed.
